MODULE CPLNG

    USE CPLNG_DATA_MOD
    USE CPLNG_INIT_MOD
    USE CPLNG_CONFIG_MOD
    USE CPLNG_EXCHANGE_MOD
    USE CPLNG_FINALIZE_MOD

    IMPLICIT NONE

    PRIVATE

    PUBLIC CPLNG_FLD_TYPE
    PUBLIC CPLNG_FLD
    PUBLIC CPLNG_IDX

    PUBLIC CPLNG_STAGE_IGNORE
    PUBLIC CPLNG_STAGE_SND
    PUBLIC CPLNG_STAGE_REC

    PUBLIC CPLNG_INIT
    PUBLIC CPLNG_CONFIG
    PUBLIC CPLNG_EXCHANGE
    PUBLIC CPLNG_FINALIZE

END MODULE CPLNG
